name: Docker Image CI

on: [push, pull_request]

jobs:

    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [6, 9, 10, 12, 14]

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker Image
              run: docker build -t govpf/node:${{ matrix.node-version }} ${{ matrix.node-version }}