name: Publish Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, 10, 12, 14, 15]
        distro: [ stretch, buster ]
    env:
      repo: "govpf/node"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Compute tags
      env:
        repo: ${{ env.repo }}
        version: ${{ matrix.version }}
        distro: ${{ matrix.distro }}
      run: |
        TAGS="${repo}:${version}-${distro}"
        if [[ $distro == 'stretch' ]]; then
          TAGS+=",${repo}:${version}"
        fi
        echo 'docker_tags<<EOF' >> $GITHUB_ENV
        echo "$TAGS" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.version }}/${{ matrix.distro }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: ${{ env.docker_tags }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2.4.2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
